# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_name', models.CharField(max_length=100)),
                ('pin_description', models.CharField(max_length=300)),
                ('pin_room', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_text', models.CharField(max_length=10)),
                ('votes', models.IntegerField(default=0)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.Pin')),
            ],
        ),
    ]
