# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-02 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import pins.models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_room',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[pins.models.validate_room]),
        ),
    ]
