# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='type',
            field=models.CharField(choices=[('c', 'Club'), ('p', 'Public'), ('r', 'Private'), ('o', 'Other')], default='p', max_length=1),
            preserve_default=False,
        ),
    ]
