# Generated by Django 2.1.3 on 2019-01-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin_type',
            field=models.CharField(choices=[('Club', 'Club'), ('Public', 'Public'), ('Private', 'Private'), ('Other', 'Other')], default='Other', max_length=10, null=True),
        ),
    ]
