# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-24 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20190422_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin_room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
