# Generated by Django 2.1.3 on 2018-12-16 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20181212_1034'),
        ('pins', '0002_pin_type'),
    ]

    operations = [
    ]
