# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20190116_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
