# Generated by Django 2.1.3 on 2019-01-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_auto_20190122_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_text',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='votes',
        ),
        migrations.AddField(
            model_name='pin',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
