# Generated by Django 2.1.3 on 2018-12-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_merge_20181216_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='pin_type',
            field=models.CharField(default='Club', max_length=10),
            preserve_default=False,
        ),
    ]
