# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import pins.models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_pin_pin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name=b'pin_type',
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_room',
            field=models.CharField(max_length=20, validators=[pins.models.validate_room]),
        ),
    ]
