# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_pin_pin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_text',
        ),
    ]
