# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-22 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_remove_vote_vote_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
