# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_auto_20190109_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='type',
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_type',
            field=models.CharField(choices=[('c', 'Club'), ('p', 'Public'), ('r', 'Private'), ('o', 'Other')], default='o', max_length=10),
            preserve_default=False,
        ),
    ]
