# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-22 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_auto_20190123_2250'),
        ('pins', '0006_pin_votes'),
    ]

    operations = [
    ]
