# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_auto_20190313_0923'),
        ('pins', '0006_pin_votes'),
    ]

    operations = [
    ]
