# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0007_merge_20190313_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='type',
        ),
    ]
